grpc:
  channels:
    carts:
      host: weavesocks-carts-grpc
    user:
      host: weavesocks-user-grpc
    payment:
      host: weavesocks-payment-grpc
    shipping:
      host: weavesocks-shipping-grpc